services:
  social-media-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=socialmediadb
