import type { Metadata } from "next";

import "./globals.css";
import { SideBar } from "@/components/side-bar";
import { auth } from "./auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className="min-h-screen">
        <SideBar userId={session?.user?.id!} />
        <div className="w-full ">
          <header className="fixed top-0 left-0 bg-black w-full py-6 flex justify-center z-10 items-center">
            <span className="text-white">Home</span>
          </header>
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
